services:
  mysql:
    image: mysql:8
    container_name: flashsale-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: flashsale
    ports:
      - "13306:3306"
    volumes:
      - ./mysql-data:/var/lib/mysql   # 数据库文件

  redis:
    image: redis:7
    container_name: flashsale-redis
    ports:
      - "16379:6379"
    volumes:
      - ./redis-data:/data            # Redis 持久化文件

  rabbitmq:
    image: rabbitmq:3.13-management
    container_name: flashsale-rabbit
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ./rabbitmq-data:/var/lib/rabbitmq  # RabbitMQ 数据

  redpanda:
    image: redpandadata/redpanda:latest
    container_name: flashsale-redpanda
    command:
      - redpanda
      - start
      - --overprovisioned
      - --smp
      - "1"
      - --memory
      - 1G
      - --reserve-memory
      - 0M
      - --node-id
      - "0"
      - --check=false
    ports:
      - "9092:9092"
    volumes:
      - ./redpanda-data:/var/lib/redpanda/data  # Redpanda 数据

#./gradlew bootRun --args='--spring.profiles.active=rabbit'
#./gradlew bootRun --args='--spring.profiles.active=kafka'
